export const BOND_SELL_LIST_REQUEST = 'BOND_SELL_LIST_REQUEST'
export const BOND_SELL_LIST_SUCCESS = 'BOND_SELL_LIST_SUCCESS'
export const BOND_SELL_LIST_FAIL = 'BOND_SELL_LIST_FAIL'

export const BOND_BUY_LIST_REQUEST = 'BOND_BUY_LIST_REQUEST'
export const BOND_BUY_LIST_SUCCESS = 'BOND_BUY_LIST_SUCCESS'
export const BOND_BUY_LIST_FAIL = 'BOND_BUY_LIST_FAIL'

export const BOND_CREATE_REQUEST = 'BOND_CREATE_REQUEST'
export const BOND_CREATE_SUCCESS = 'BOND_CREATE_SUCCESS'
export const BOND_CREATE_FAIL = 'BOND_CREATE_FAIL'
export const BOND_CREATE_RESET = 'BOND_CREATE_RESET'

export const BOND_BUY_UPDATE_REQUEST = 'BOND_BUY_UPDATE_REQUEST'
export const BOND_BUY_UPDATE_SUCCESS = 'BOND_BUY_UPDATE_SUCCESS'
export const BOND_BUY_UPDATE_FAIL = 'BONF_BUY_UPDATE_FAIL'
export const BOND_BUY_UPDATE_RESET = 'BONF_BUY_UPDATE_RESET'

export const BOND_DOLLAR_VALUE_REQUEST = 'BOND_DOLLAR_VALUE_REQUEST'
export const BOND_DOLLAR_VALUE_SUCCESS = 'BOND_DOLLAR_VALUE_SUCCESS'
export const BOND_DOLLAR_VALUE_FAIL = 'BOND_DOLLAR_VALUE_FAIL'

export const BOND_MONEY_TYPE_SET = 'BOND_MONEY_TYPE_SET'

